spring.application.name=hospitalManagement

# Oracle DB Connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=arman
spring.datasource.password=rohan
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1



#security config
#spring.security.user.name=arman
#spring.security.user.password=king
jwt.secretKey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7y